name: Action_Hello_World
on:
  push:
    branches: ["master"]

  jobs: 
    GitHub-Actions-hello:
      runs-on: ubuntu-latest
      steps:
        -name: Checkout Code
        uses: action/checkout@v3
        -name:
        run: pyton hello.py
      
